session_name: work

windows:
- window_name: work
  focus: true
  layout: "577a,214x62,0,0[214x39,0,0,4,214x22,0,40{106x22,0,40,5,107x22,107,40,6}]"
  panes:
    - shell_command:
        - yazi
      focus: true
    - pane
    - pane

- window_name: "music"
  focus: false
  layout: "c3f7,214x62,0,0[214x30,0,0,7,214x31,0,31,8]"
  panes:
    - shell_command:
        - btop
    - shell_command:
        - yt pl PLBFICLTzW2LckbdM1Ri6BBfpeSPwRYzXe
      focus: true
