tmux_options: -2
session_name: work

windows:
- window_name: work
  focus: true
  layout: c50c,353x84,0,0[353x56,0,0,1,353x27,0,57{176x27,0,57,2,176x27,177,57,5}]
  panes:
    - yazi
    - pane
    - pane

- window_name: music
  focus: false
  panes:
    - yt pl PLBFICLTzW2LckbdM1Ri6BBfpeSPwRYzXe