[tools]
go = "latest"
python = "latest"
rust = "latest"

bat = "latest"
fd = "latest"
fzf = "latest"
imagemagick = "latest"
jq = "latest"
neovim = "latest"
podman = "latest"
ripgrep = "latest"
shellcheck = "latest"
tmux = "latest"
trivy = "latest"
uv = "latest"
vim = "latest"
yazi = "latest"
zoxide = "latest"

[settings]
experimental = true

[env]
XDG_CONFIG_HOME = "{{env.HOME}}/.config"
SHELL = "/bin/bash"
EDITOR = "nvim"
MISE_PYTHON_DEFAULT_PACKAGES_FILE = "{{env.HOME}}/.config/mise/default-python-packages"
