[tools]
# language runtime
go = "latest"
python = "latest"
rust = "latest"
node = "latest"
npm = "latest"
bun = "latest"
deno = "latest"
lua = "5.1.5"
"aqua:jdx/usage" = "latest"

# dev package
"aqua:ajeetdsouza/zoxide" = "latest"
"aqua:aristocratos/btop" = { version = "latest", os = ["linux"] }
"aqua:astral-sh/uv" = "latest"
"aqua:bcicen/ctop" = "latest"
"aqua:BurntSushi/ripgrep" = "latest"
"aqua:eza-community/eza" = { version = "latest", os = ["linux"] }
"aqua:jesseduffield/lazydocker" = "latest"
"aqua:jesseduffield/lazygit" = "latest"
"aqua:jqlang/jq" = "latest"
"aqua:junegunn/fzf" = "latest"
"aqua:koalaman/shellcheck" = "latest"
"aqua:neovim/neovim" = "latest"
"aqua:pypa/pipx" = { version = "latest", os = ["linux", "macos"] }
"aqua:sharkdp/bat" = "latest"
"aqua:sharkdp/fd" = "latest"
"aqua:sxyazi/yazi" = "latest"
"aqua:x-motemen/ghq" = "latest"
"asdf:mise-plugins/mise-eza" = { version = "latest", os = ["macos"] }
"github:tmux/tmux-builds" = "latest"

# python
"pipx:debugpy" = "latest"
"pipx:httpie" = "latest" 
"pipx:tmuxp" = "latest"
"pipx:pipdeptree" = "latest"
"pipx:pynvim" = "latest"
"pipx:ruff" = "latest"
"pipx:yewtube" = { version = "latest", uvx_args = "--with httpx==0.27.2,pip" }
"pipx:posting" = "latest"

# go
"go:github.com/jorgerojas26/lazysql" = "latest"

# node
"npm:@google/gemini-cli" = "latest"

# github
"github:cli/cli" = { version = "latest", exe = "gh", strip_components = 1 }

[settings]
experimental = true
pipx.uvx = true
github.github_attestations = false
npm.package_manager = "bun"

[env]
XDG_CONFIG_HOME = "{{env.HOME}}/.config"
SHELL = "/bin/bash"
EDITOR = "nvim"
MISE_DATA_DIR = "{{env.HOME}}/.local/share/mise"
MISE_STATE_DIR="{{env.HOME}}/.local/state/mise"
MISE_CACHE_DIR="{{env.HOME}}/.cache/mise"
MISE_CONFIG_DIR="{{env.HOME}}/.config/mise"
MISE_NODE_COREPACK = "true"
