[tools]
# language runtime
go = "latest"
python = "latest"
rust = "latest"
deno = "latest"
lua = "5.1.5"
"aqua:jdx/usage" = "latest"

# dev package
"aqua:ajeetdsouza/zoxide" = "latest"
"aqua:aristocratos/btop" = { version = "latest", os = ["linux"] }
"aqua:astral-sh/uv" = "latest"
"aqua:bcicen/ctop" = "latest"
"aqua:BurntSushi/ripgrep" = "latest"
"aqua:cli/cli" = "latest"
"aqua:eza-community/eza" = { version = "latest", os = ["linux"] }
"aqua:jqlang/jq" = "latest"
"aqua:junegunn/fzf" = "latest"
"aqua:koalaman/shellcheck" = "latest"
"aqua:neovim/neovim" = "latest"
"aqua:pypa/pipx" = { version = "latest", os = ["linux", "macos"] }
"aqua:sharkdp/bat" = "latest"
"aqua:sharkdp/fd" = "latest"
"aqua:sxyazi/yazi" = "latest"
"aqua:x-motemen/ghq" = "latest"
"asdf:mise-plugins/mise-eza" = { version = "latest", os = ["macos"] }
"github:tmux/tmux-builds" = "latest"

# python
"pipx:debugpy" = "latest"
"pipx:httpie" = "latest" 
"pipx:tmuxp" = "latest"
"pipx:pipdeptree" = "latest"
"pipx:pynvim" = "latest"
"pipx:ruff" = "latest"
"pipx:yewtube" = { version = "latest", uvx_args = "--with httpx==0.27.2,pip" }

[settings]
experimental = true

[env]
XDG_CONFIG_HOME = "{{env.HOME}}/.config"
SHELL = "/bin/bash"
EDITOR = "nvim"
