name: Setup(init) Nightly

on:
  schedule:
    - cron: '0 18 * * *'  # JST 03:00
  workflow_dispatch:

jobs:
  ubuntu-init:
    name: Nightly init on Ubuntu
    runs-on: ubuntu-latest
    container:
      image: ubuntu:22.04

    steps:
      - name: Install base packages
        run: |
          set -eux
          apt-get update
          DEBIAN_FRONTEND=noninteractive apt-get install -y \
            git sudo make ca-certificates curl

      - name: Checkout
        uses: actions/checkout@v4

      - name:  Initialize development environment
        env:
          DOTPATH: ${{ github.workspace }}
          TERM: xterm-256color
        run: |
          set -eux
          make init